<a href="https://colab.research.google.com/github/kalxdoc/Research_pac1/blob/main/RE1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print ("hello ")

hello

In [7]:
from numpy import mean
import pandas as pd
from sklearn.impute import SimpleImputer
df=pd.read_csv("/content/dhaka_soil_data.csv")
print("--1.First row")
display(df.head())
print("--- 1. IDENTIFY MISSING VALUES ---")
# .isnull().sum() is your best friend. It counts the exact number of
# missing cells in every single column.
missing_counts = df.isnull().sum()
print(missing_counts)
print("-" * 30)
print("\n---SKlearm method---")
df_sklearn=df.copy()
imputer=SimpleImputer(strategy='mean')
df_sklearn[['Distance_to_Tannery_m']]=imputer.fit_transform(df_sklearn[['distance']])

--1.First row

,Sample_ID,Latitude,Longitude,Land_Use,Distance_to_Tannery_m,Soil_pH,Lead_mg_kg,Cadmium_mg_kg
0,S001,23.7383,90.3688,Industrial,450.5,6.2,145.2,2.4
1,S002,23.7412,90.3721,Residential,1200.0,6.8,42.1,0.8
2,S003,23.7355,90.3650,Industrial,150.2,5.9,210.5,3.1
3,S004,23.7450,90.3800,Commercial,2500.8,7.1,28.4,0.3
4,S005,23.7501,90.3902,Residential,NaN,6.9,18.5,0.1

--- 1. IDENTIFY MISSING VALUES ---
Sample_ID                0
Latitude                 0
Longitude                0
Land_Use                 0
Distance_to_Tannery_m    1
Soil_pH                  0
Lead_mg_kg               0
Cadmium_mg_kg            0
dtype: int64
------------------------------

---SKlearm method---

In [ ]:
from numpy import mean
import pandas as pd
from sklearn.impute import SimpleImputer
df=pd.read_csv("/content/dhaka_soil_data.csv")
print("--1.First row")
display(df.head())
print("--- 1. IDENTIFY MISSING VALUES ---")
# .isnull().sum() is your best friend. It counts the exact number of
# missing cells in every single column.
missing_counts = df.isnull().sum()
print(missing_counts)
print("-" * 30)
print("\n---SKlearm method---")
df_sklearn=df.copy()
imputer=SimpleImputer(strategy='mean')
df_sklearn[['Distance_to_Tannery_m']]=imputer.fit_transform(df_sklearn[['']])

--1.First row

,Sample_ID,Latitude,Longitude,Land_Use,Distance_to_Tannery_m,Soil_pH,Lead_mg_kg,Cadmium_mg_kg
0,S001,23.7383,90.3688,Industrial,450.5,6.2,145.2,2.4
1,S002,23.7412,90.3721,Residential,1200.0,6.8,42.1,0.8
2,S003,23.7355,90.3650,Industrial,150.2,5.9,210.5,3.1
3,S004,23.7450,90.3800,Commercial,2500.8,7.1,28.4,0.3
4,S005,23.7501,90.3902,Residential,NaN,6.9,18.5,0.1

--- 1. IDENTIFY MISSING VALUES ---
Sample_ID                0
Latitude                 0
Longitude                0
Land_Use                 0
Distance_to_Tannery_m    1
Soil_pH                  0
Lead_mg_kg               0
Cadmium_mg_kg            0
dtype: int64
------------------------------

---SKlearm method---

In [ ]:
from numpy import mean
import pandas as pd
from sklearn.impute import SimpleImputer
df=pd.read_csv("/content/dhaka_soil_data.csv")
print("--1.First row")
display(df.head())
print("--- 1. IDENTIFY MISSING VALUES ---")
# .isnull().sum() is your best friend. It counts the exact number of
# missing cells in every single column.
missing_counts = df.isnull().sum()
print(missing_counts)
print("-" * 30)
print("\n---SKlearm method---")
df_sklearn=df.copy()
imputer=SimpleImputer(strategy='mean')
df_sklearn[['Distance_to_Tannery_m']]=imputer.fit_transform(df_sklearn[['']])

--1.First row

,Sample_ID,Latitude,Longitude,Land_Use,Distance_to_Tannery_m,Soil_pH,Lead_mg_kg,Cadmium_mg_kg
0,S001,23.7383,90.3688,Industrial,450.5,6.2,145.2,2.4
1,S002,23.7412,90.3721,Residential,1200.0,6.8,42.1,0.8
2,S003,23.7355,90.3650,Industrial,150.2,5.9,210.5,3.1
3,S004,23.7450,90.3800,Commercial,2500.8,7.1,28.4,0.3
4,S005,23.7501,90.3902,Residential,NaN,6.9,18.5,0.1

--- 1. IDENTIFY MISSING VALUES ---
Sample_ID                0
Latitude                 0
Longitude                0
Land_Use                 0
Distance_to_Tannery_m    1
Soil_pH                  0
Lead_mg_kg               0
Cadmium_mg_kg            0
dtype: int64
------------------------------

---SKlearm method---

In [17]:
from numpy import mean
import pandas as pd
from sklearn.impute import SimpleImputer
df=pd.read_csv("/content/dhaka_soil_data.csv")
print("--1.First row")
display(df.head())
print("--- 1. IDENTIFY MISSING VALUES ---")
# .isnull().sum() is your best friend. It counts the exact number of
# missing cells in every single column.
missing_counts = df.isnull().sum()
print(missing_counts)
print("-" * 30)
print("\n---SKlearm method---")
df_sklearn=df.copy()
imputer=SimpleImputer(strategy='mean')
df_sklearn[['Distance_to_Tannery_m']]=imputer.fit_transform(df_sklearn[['Distance_to_Tannery_m']])
print(f"missin values in column: {df_sklearn['Distance_to_Tannery_m'].isnull().sum()}")
print(f"Calculated Mean Distance: {imputer.statistics_[0]:.2f} meters")

--1.First row

,Sample_ID,Latitude,Longitude,Land_Use,Distance_to_Tannery_m,Soil_pH,Lead_mg_kg,Cadmium_mg_kg
0,S001,23.7383,90.3688,Industrial,450.5,6.2,145.2,2.4
1,S002,23.7412,90.3721,Residential,1200.0,6.8,42.1,0.8
2,S003,23.7355,90.3650,Industrial,150.2,5.9,210.5,3.1
3,S004,23.7450,90.3800,Commercial,2500.8,7.1,28.4,0.3
4,S005,23.7501,90.3902,Residential,NaN,6.9,18.5,0.1

--- 1. IDENTIFY MISSING VALUES ---
Sample_ID                0
Latitude                 0
Longitude                0
Land_Use                 0
Distance_to_Tannery_m    1
Soil_pH                  0
Lead_mg_kg               0
Cadmium_mg_kg            0
dtype: int64
------------------------------

---SKlearm method---
missin values in column: 0
Calculated Mean Distance: 1558.58 meters