<a href="https://colab.research.google.com/github/kalxdoc/Research_pac1/blob/main/RE1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print ("hello ")

hello

In [ ]:
from numpy import mean
import pandas as pd
from sklearn.impute import SimpleImputer
df=pd.read_csv("/content/dhaka_soil_data.csv")
print("--1.First row")
display(df.head())
print("--- 1. IDENTIFY MISSING VALUES ---")
# .isnull().sum() is your best friend. It counts the exact number of
# missing cells in every single column.
missing_counts = df.isnull().sum()
print(missing_counts)
print("-" * 30)
print("\n---SKlearm method---")
df_sklearn=df.copy()
imputer=SimpleImputer(strategy='mean')
df_sklearn[['Distance_to_Tannery_m']]=imputer.fit_transform(df_sklearn[['distance']])

--1.First row

,Sample_ID,Latitude,Longitude,Land_Use,Distance_to_Tannery_m,Soil_pH,Lead_mg_kg,Cadmium_mg_kg
0,S001,23.7383,90.3688,Industrial,450.5,6.2,145.2,2.4
1,S002,23.7412,90.3721,Residential,1200.0,6.8,42.1,0.8
2,S003,23.7355,90.3650,Industrial,150.2,5.9,210.5,3.1
3,S004,23.7450,90.3800,Commercial,2500.8,7.1,28.4,0.3
4,S005,23.7501,90.3902,Residential,NaN,6.9,18.5,0.1

--- 1. IDENTIFY MISSING VALUES ---
Sample_ID                0
Latitude                 0
Longitude                0
Land_Use                 0
Distance_to_Tannery_m    1
Soil_pH                  0
Lead_mg_kg               0
Cadmium_mg_kg            0
dtype: int64
------------------------------

---SKlearm method---

In [ ]:
from numpy import mean
import pandas as pd
from sklearn.impute import SimpleImputer
df=pd.read_csv("/content/dhaka_soil_data.csv")
print("--1.First row")
display(df.head())
print("--- 1. IDENTIFY MISSING VALUES ---")
# .isnull().sum() is your best friend. It counts the exact number of
# missing cells in every single column.
missing_counts = df.isnull().sum()
print(missing_counts)
print("-" * 30)
print("\n---SKlearm method---")
df_sklearn=df.copy()
imputer=SimpleImputer(strategy='mean')
df_sklearn[['Distance_to_Tannery_m']]=imputer.fit_transform(df_sklearn[['']])

--1.First row

,Sample_ID,Latitude,Longitude,Land_Use,Distance_to_Tannery_m,Soil_pH,Lead_mg_kg,Cadmium_mg_kg
0,S001,23.7383,90.3688,Industrial,450.5,6.2,145.2,2.4
1,S002,23.7412,90.3721,Residential,1200.0,6.8,42.1,0.8
2,S003,23.7355,90.3650,Industrial,150.2,5.9,210.5,3.1
3,S004,23.7450,90.3800,Commercial,2500.8,7.1,28.4,0.3
4,S005,23.7501,90.3902,Residential,NaN,6.9,18.5,0.1

--- 1. IDENTIFY MISSING VALUES ---
Sample_ID                0
Latitude                 0
Longitude                0
Land_Use                 0
Distance_to_Tannery_m    1
Soil_pH                  0
Lead_mg_kg               0
Cadmium_mg_kg            0
dtype: int64
------------------------------

---SKlearm method---

In [ ]:
from numpy import mean
import pandas as pd
from sklearn.impute import SimpleImputer
df=pd.read_csv("/content/dhaka_soil_data.csv")
print("--1.First row")
display(df.head())
print("--- 1. IDENTIFY MISSING VALUES ---")
# .isnull().sum() is your best friend. It counts the exact number of
# missing cells in every single column.
missing_counts = df.isnull().sum()
print(missing_counts)
print("-" * 30)
print("\n---SKlearm method---")
df_sklearn=df.copy()
imputer=SimpleImputer(strategy='mean')
df_sklearn[['Distance_to_Tannery_m']]=imputer.fit_transform(df_sklearn[['']])

--1.First row

,Sample_ID,Latitude,Longitude,Land_Use,Distance_to_Tannery_m,Soil_pH,Lead_mg_kg,Cadmium_mg_kg
0,S001,23.7383,90.3688,Industrial,450.5,6.2,145.2,2.4
1,S002,23.7412,90.3721,Residential,1200.0,6.8,42.1,0.8
2,S003,23.7355,90.3650,Industrial,150.2,5.9,210.5,3.1
3,S004,23.7450,90.3800,Commercial,2500.8,7.1,28.4,0.3
4,S005,23.7501,90.3902,Residential,NaN,6.9,18.5,0.1

--- 1. IDENTIFY MISSING VALUES ---
Sample_ID                0
Latitude                 0
Longitude                0
Land_Use                 0
Distance_to_Tannery_m    1
Soil_pH                  0
Lead_mg_kg               0
Cadmium_mg_kg            0
dtype: int64
------------------------------

---SKlearm method---

In [ ]:
from numpy import mean
import pandas as pd
from sklearn.impute import SimpleImputer
df=pd.read_csv("/content/dhaka_soil_data.csv")
print("--1.First row")
display(df.head())
print("--- 1. IDENTIFY MISSING VALUES ---")
# .isnull().sum() is your best friend. It counts the exact number of
# missing cells in every single column.
missing_counts = df.isnull().sum()
print(missing_counts)
print("-" * 30)
print("\n---SKlearm method---")
df_sklearn=df.copy()
imputer=SimpleImputer(strategy='mean')
df_sklearn[['Distance_to_Tannery_m']]=imputer.fit_transform(df_sklearn[['Distance_to_Tannery_m']])
print(f"missin values in column: {df_sklearn['Distance_to_Tannery_m'].isnull().sum()}")
print(f"Calculated Mean Distance: {imputer.statistics_[0]:.2f} meters")

--1.First row

,Sample_ID,Latitude,Longitude,Land_Use,Distance_to_Tannery_m,Soil_pH,Lead_mg_kg,Cadmium_mg_kg
0,S001,23.7383,90.3688,Industrial,450.5,6.2,145.2,2.4
1,S002,23.7412,90.3721,Residential,1200.0,6.8,42.1,0.8
2,S003,23.7355,90.3650,Industrial,150.2,5.9,210.5,3.1
3,S004,23.7450,90.3800,Commercial,2500.8,7.1,28.4,0.3
4,S005,23.7501,90.3902,Residential,NaN,6.9,18.5,0.1

--- 1. IDENTIFY MISSING VALUES ---
Sample_ID                0
Latitude                 0
Longitude                0
Land_Use                 0
Distance_to_Tannery_m    1
Soil_pH                  0
Lead_mg_kg               0
Cadmium_mg_kg            0
dtype: int64
------------------------------

---SKlearm method---
missin values in column: 0
Calculated Mean Distance: 1558.58 meters

In [ ]:
#Convert any categorical text data (like "Industrial Area" or "Residential Area") into numbers using LabelEncoder or OneHotEncoder
import pandas as pd
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
df=pd.read_csv("/content/dhaka_soil_data.csv")
print("--- ORIGINAL DATA ---")
display(df[['Sample_ID', 'Land_Use']].head())
print("\n--- METHOD A: Label Encoding (For Ranked Data) ---")
# 1. Initialize the encoder
label_enc = LabelEncoder()

# 2. Fit and transform the column
df_label = df.copy()
df_label['Land_Use_Encoded'] = label_enc.fit_transform(df_label['Land_Use'])
display(df_label[['Sample_ID', 'Land_Use', 'Land_Use_Encoded']].head())
print("\n--- METHOD B: One-Hot Encoding via Pandas (For Unranked Data) ---")
# Pandas has a built-in function called 'get_dummies' which is the easiest
# way for beginners to do One-Hot Encoding.
df_onehot = pd.get_dummies(df, columns=['Land_Use'], dtype=int)

# Notice how the original 'Land_Use' column is gone, replaced by new binary columns!
display(df_onehot.head())

--- ORIGINAL DATA ---

  Sample_ID     Land_Use
0      S001   Industrial
1      S002  Residential
2      S003   Industrial
3      S004   Commercial
4      S005  Residential

--- METHOD A: Label Encoding (For Ranked Data) ---

  Sample_ID     Land_Use  Land_Use_Encoded
0      S001   Industrial                 2
1      S002  Residential                 3
2      S003   Industrial                 2
3      S004   Commercial                 1
4      S005  Residential                 3

--- METHOD B: One-Hot Encoding via Pandas (For Unranked Data) ---

  Sample_ID  Latitude  ...  Land_Use_Industrial  Land_Use_Residential
0      S001   23.7383  ...                    1                     0
1      S002   23.7412  ...                    0                     1
2      S003   23.7355  ...                    1                     0
3      S004   23.7450  ...                    0                     0
4      S005   23.7501  ...                    0                     1

[5 rows x 11 columns]

In [ ]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
df=pd.read_csv("/content/dhaka_soil_data.csv")
print("--- 1. LIST ALL COLUMNS ---")
print(df.columns.tolist())
print("\n--- 2. AUTOMATED SPATIAL FEATURE CHECK ---")
required_spatial_features = ['Latitude', 'Longitude', 'Distance_to_Tannery_m']
missing_features = [col for col in required_spatial_features if col not in df.columns]
if not missing_features:
    print("✅ SUCCESS: All required spatial features are present! The data is ready for mapping.")
else:
    print(f"❌ WARNING: Alert your team! You are missing these columns: {missing_features}")

--- 1. LIST ALL COLUMNS ---
['Sample_ID', 'Latitude', 'Longitude', 'Land_Use', 'Distance_to_Tannery_m', 'Soil_pH', 'Lead_mg_kg', 'Cadmium_mg_kg']

--- 2. AUTOMATED SPATIAL FEATURE CHECK ---
✅ SUCCESS: All required spatial features are present! The data is ready for mapping.

In [ ]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
df=pd.read_csv("/content/dhaka_soil_data.csv")
print("--- 1. LIST ALL COLUMNS ---")
print(df.columns.tolist())
print("\n--- 2. AUTOMATED SPATIAL FEATURE CHECK ---")
required_spatial_features = ['Latitude', 'Longitude', 'Distance_to_Tannery_m']
missing_features = [col for col in required_spatial_features if col not in df.columns]
if not missing_features:
    print("✅ SUCCESS: All required spatial features are present! The data is ready for mapping.")
else:
    print(f"❌ WARNING: Alert your team! You are missing these columns: {missing_features}")

--- 1. LIST ALL COLUMNS ---
['Sample_ID', 'Latitude', 'Longitude', 'Land_Use', 'Distance_to_Tannery_m', 'Soil_pH', 'Lead_mg_kg', 'Cadmium_mg_kg']

--- 2. AUTOMATED SPATIAL FEATURE CHECK ---
✅ SUCCESS: All required spatial features are present! The data is ready for mapping.

In [ ]:
from sklearn.model_selection import train_test_split
import pandas as pd

df=pd.read_csv("/content/dhaka_soil_data.csv")
X = df.drop(columns=['Lead_mg_kg', 'Sample_ID'])
y = df['Lead_mg_kg']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
print("--- DATA SHAPES ---")
print(f"Total rows in original dataset: {len(df)}")
print(f"Rows given to the AI to study (X_train): {len(X_train)}")
print(f"Rows hidden for final testing (X_test): {len(X_test)}")

--- DATA SHAPES ---
Total rows in original dataset: 7
Rows given to the AI to study (X_train): 5
Rows hidden for final testing (X_test): 2